const games = [
    ['water','bottle','up','turn','over','work'],
    ['bottle','kneck','tie','down','side','street'],
    ['live','stream','line','back','bone','marrow'],
    ['home','school','bus','stop','light','switch'],
    ['my','self','center','piece','together','forever'],
    ['french','fry','pan','cake','mix','tape'],
    ['post','office','work','day','time','travel'],
    ['soy','milk','man','cave','dive','bar'],
    ['vegetable','garden','tool','shed','tears','apart'],
    ['cough','drop','out','front','desk','job'],
    ['phone','call','off','chance','upon','request'],
    ['last','straw','berry','picking','fights','off'],
    ['tissue','paper','boy','friend','band','wagon'],
    ['wheel','chair','board','member','state','capital'],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    []
]

export default games;